name: cross_file_example
description: Example of Cross File plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file:
    # When depending on this package from a real application you should use:
    #   cross_file: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  cross_file:
    path: ../

flutter:

  uses-material-design: true
