name: google_adsense_ad_placement_api_web
description: Dart classes to interact with Google's AdSense Ad Placement API in Flutter Web applications.
version: 1.0.0
repository: https://github.com/flutter/packages/tree/main/packages/google_adsense_ad_placement_api_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_adsense_ad_placement_api_web%22

environment:
  sdk: ^3.4.4

dependencies:
  web: "^1.1.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

platforms:
  web:

topics:
  - google-adsense
  - adsense-ad-placement-api
  - advertising
  - web
