name: video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.0
  video_player_platform_interface: ">=6.1.0 <7.0.0"
  video_player_web:
    path: ../
  web: '>=0.3.0 <0.5.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
