name: css_colors_example
description: Demonstrates how to use CSS Colors.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  css_colors:
    # When depending on this package from a real application you should use:
    #   css_colors: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
