'p: animations':
  - any:
    - packages/animations/**/*

'p: camera':
  - any:
    - packages/camera/**/*

'p: cross_file':
  - any:
    - packages/cross_file/**/*

'p: css_colors':
  - any:
    - packages/css_colors/**/*

'p: cupertino_icons':
  - any:
    - third_party/packages/cupertino_icons/**/*

'p: dynamic_layouts':
  - any:
    - packages/dynamic_layouts/**/*

'p: espresso':
  - any:
    - packages/espresso/**/*

'p: extension_google_sign_in_as_googleapis_auth':
  - any:
    - packages/extension_google_sign_in_as_googleapis_auth/**/*

'p: file_selector':
  - any:
    - packages/file_selector/**/*

'p: flutter_adaptive_scaffold':
  - any:
    - packages/flutter_adaptive_scaffold/**/*

'p: flutter_image':
  - any:
    - packages/flutter_image/**/*

'p: flutter_lints':
  - any:
    - packages/flutter_lints/**/*

'p: flutter_markdown':
  - any:
    - packages/flutter_markdown/**/*

'p: flutter_migrate':
  - any:
    - packages/flutter_migrate/**/*

'p: flutter_plugin_android_lifecycle':
  - any:
    - packages/flutter_plugin_android_lifecycle/**/*

'p: flutter_template_images':
  - any:
    - packages/flutter_template_images/**/*

'p: go_router':
  - any:
    - packages/go_router/**/*

'p: go_router_builder':
  - any:
    - packages/go_router_builder/**/*

'p: google_identity_services':
  - any:
    - packages/google_indentity_services_web/**

'p: google_maps_flutter':
  - any:
    - packages/google_maps_flutter/**/*

'p: google_sign_in':
  - any:
    - packages/google_sign_in/**/*

'p: image_picker':
  - any:
    - packages/image_picker/**/*

'p: in_app_purchase':
  - any:
    - packages/in_app_purchase/**/*

'p: ios_platform_images':
  - any:
    - packages/ios_platform_images/**/*

'p: local_auth':
  - any:
    - packages/local_auth/**/*

'p: metrics_center':
  - any:
    - packages/metrics_center/**/*

'p: multicast_dns':
  - any:
    - packages/multicast_dns/**/*

'p: palette_generator':
  - any:
    - packages/palette_generator/**/*

'p: path_provider':
  - any:
    - packages/path_provider/**/*

'p: pigeon':
  - any:
    - packages/pigeon/**/*

'p: plugin_platform_interface':
  - any:
    - packages/plugin_platform_interface/**/*

'p: pointer_interceptor':
  - any:
    - packages/pointer_interceptor/**/*

'p: quick_actions':
  - any:
    - packages/quick_actions/**/*

'p: rfw':
  - any:
    - packages/rfw/**/*

'p: shared_preferences':
  - any:
    - packages/shared_preferences/**/*

'p: standard_message_codec':
  - any:
    - packages/standard_message_codec/**/*

'p: url_launcher':
  - any:
    - packages/url_launcher/**/*

'p: video_player':
  - any:
    - packages/video_player/**/*

'p: web_benchmarks':
  - any:
    - packages/web_benchmarks/**/*

'p: webview_flutter':
  - any:
    - packages/webview_flutter/**/*

'p: xdg_directories':
  - any:
    - packages/xdg_directories/**/*

'platform-android':
  - any:
    - packages/*/*_android/**/*
    - packages/**/android/**/*

'platform-ios':
  - any:
    - packages/*/*_ios/**/*
    - packages/*/*_storekit/**/*
    - packages/*/*_wkwebview/**/*
    - packages/**/ios/**/*

'platform-linux':
  - any:
    - packages/*/*_linux/**/*
    - packages/**/linux/**/*

'platform-macos':
  - any:
    - packages/*/*_macos/**/*
    - packages/**/macos/**/*

'platform-web':
  - any:
    - packages/*/*_web/**/*
    - packages/**/web/**/*

'platform-windows':
  - any:
    - packages/*/*_windows/**/*
    - packages/**/windows/**/*

