---
dependencies:
  camera_android: ^0.10.7
  camera_avfoundation: ^0.9.14
  camera_platform_interface: ^2.5.2
  camera_web: ^0.3.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  quiver: ^3.0.0
description: A Flutter plugin for controlling the camera. Supports previewing the camera feed, capturing images and video, and streaming image buffers to Dart.
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  plugin_platform_interface: ^2.0.0
  video_player: ^2.0.0
environment:
  flutter: '>=3.3.0'
  sdk: '>=2.18.0 <4.0.0'
flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
name: camera
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
version: 0.10.6