task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 8G
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: analyze
      script: ./script/incremental_build.sh analyze --custom-analysis=web_benchmarks/testing/test_app
    - name: publishable
      script: ./script/check_publish.sh
      depends_on:
        - analyze
    - name: test+format
      format_script: ./script/incremental_build.sh format --travis --clang-format=clang-format-5.0
      test_script: ./script/incremental_build.sh test
      depends_on:
        - analyze
    - name: build-apks+java-test
      env:
        matrix:
          BUILD_SHARDING: "--shardIndex 0 --shardCount 2"
          BUILD_SHARDING: "--shardIndex 1 --shardCount 2"
      script:
        - ./script/incremental_build.sh build-examples --apk
        - ./script/incremental_build.sh java-test  # must come after apk build
      depends_on:
        - analyze
    - name: web_benchmarks_test
      script:
        - mkdir .chromium
        # To update Chromium version used for testing, set CHROMIUM_BUILD to the desired build of Chromium.
        #
        # Chromium builds can be located here: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/
        - CHROMIUM_BUILD=768968 wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${CHROMIUM_BUILD}%2Fchrome-linux.zip?alt=media -O .chromium/chromium.zip
        - unzip .chromium/chromium.zip -d .chromium/
        - export CHROME_EXECUTABLE=$(pwd)/.chromium/chrome-linux/chrome
        - echo $CHROME_EXECUTABLE
        - $CHROME_EXECUTABLE --version
        - flutter config --enable-web
        - cd packages/web_benchmarks/testing/test_app
        - flutter packages get
        - cd ../..
        - flutter packages get
        - dart testing/web_benchmarks_test.dart

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: build-ipas
  osx_instance:
    image: high-sierra-xcode-9.4.1
  env:
    PATH: $PATH:/usr/local/bin
    matrix:
      BUILD_SHARDING: "--shardIndex 0 --shardCount 2"
      BUILD_SHARDING: "--shardIndex 1 --shardCount 2"
  setup_script:
    - pod repo update
    - git clone https://github.com/flutter/flutter.git
    - git fetch origin master
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
    - pub global activate flutter_plugin_tools
  build_script:
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - ./script/incremental_build.sh build-examples --ipa

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: local_tests
  osx_instance:
    image: catalina-flutter
  env:
    PATH: $PATH:/usr/local/bin
  setup_script:
    - pod repo update
    - git fetch origin master
    - flutter doctor
    - pub global activate flutter_plugin_tools
    - brew install clang-format
  build_script:
    - ./script/local_tests.sh
