gcp_credentials: ENCRYPTED[!0e63b52bd7e4fda1cd7b7bf2b4fe515a27fadbeaced01f5ad8b699b81d3611ed64c5d3271bcd8426dd914ef41cba48a0!]

env:
  CHANNEL: "master" # Default to master when not explicitly set by a task.

tool_setup_template: &TOOL_SETUP_TEMPLATE
  tool_setup_script:
    - git fetch origin master # To set FETCH_HEAD for "git merge-base" to work
    # Pinned version of the plugin tools, to avoid breakage in this repository
    # when pushing updates from flutter/plugins.
    - dart pub global activate flutter_plugin_tools 0.3.0

flutter_upgrade_template: &FLUTTER_UPGRADE_TEMPLATE
  upgrade_flutter_script:
    - flutter channel $CHANNEL
    - flutter upgrade
    - flutter doctor
  << : *TOOL_SETUP_TEMPLATE

task:
  name: local_tests
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  osx_instance:
    image: big-sur-xcode-12.4
  env:
    PATH: $PATH:/usr/local/bin
  << : *FLUTTER_UPGRADE_TEMPLATE
  java_test_one_script:
    - java -version
  java_test_one_script:
    - java --version
