# Run on PRs and main branch post submit only. Don't run tests when tagging.
only_if: $CIRRUS_TAG == '' && ($CIRRUS_PR != '' || $CIRRUS_BRANCH == 'main')

setup_template: &SETUP_TEMPLATE
  upgrade_flutter_script:
    # Ensure that the repository has everything.
    - cd $FLUTTER_HOME
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch origin
    # Switch to the pinned master version.
    - PINNED_VERSION=$(< .ci/flutter_master.version)
    - git checkout $TARGET_TREEISH
    # Run doctor to allow auditing of what version of Flutter the run is using.
    - flutter doctor -v
  tool_setup_script:
    - .ci/scripts/prepare_tool.sh

task:
  << : *SETUP_TEMPLATE
  gke_container:
    dockerfile: .ci/Dockerfile
    builder_image_name: docker-builder-linux # gce vm image
    builder_image_project: flutter-cirrus
    cluster_name: test-cluster
    zone: us-central1-a
    namespace: default
  matrix:
    # TODO(stuartmorgan): Migrate this to LUCI; See check_version.sh.
    - name: version_check
      only_if: $CIRRUS_PR != ''
      version_script:
        - ./script/tool_runner.sh version-check --check-for-missing-changes --pr-labels="$CIRRUS_PR_LABELS"
