name: go_router_examples
description: go_router examples
version: 3.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  adaptive_navigation: ^0.0.7
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  go_router:
    path: ..
  logging: ^1.0.2
  package_info_plus: ^1.4.3+1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
