name: pointer_interceptor_ios_example
description: "Demonstrates how to use the pointer_interceptor_ios plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.0-134.0.dev <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  pointer_interceptor:
    path: ../../pointer_interceptor
#  pointer_interceptor_ios:
#    # When depending on this package from a real application you should use:
#    #   pointer_interceptor_ios: ^x.y.z
#    # See https://dart.dev/tools/pub/dependencies#version-constraints
#    # The example app is bundled with the plugin so we use a path dependency on
#    # the parent directory to use the current plugin's version.
#    path: ../../pointer_interceptor_ios
  pointer_interceptor_platform_interface:
    path: ../../pointer_interceptor_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

