name: xdg_directories
description: A Dart package for reading XDG directory configuration information on Linux.
version: 0.2.0-nullsafety.0
homepage: https://github.com/flutter/packages/tree/master/packages/xdg_directories

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  meta: ">=1.2.2 <2.0.0"
  path: ">=1.6.4 <2.0.0"
  process: ^4.0.0-nullsafety

dev_dependencies:
  mockito: ^5.0.0-nullsafety
  test: ^1.15.3
