name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter


# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
dependency_overrides:

  camera_platform_interface: 
    path: ../../../camera/camera_platform_interface
  camera_web: 
    path: ../../../camera/camera_web

dev_dependencies:
  async: ^2.5.0
  camera_platform_interface:
  camera_web:
  cross_file: ^0.3.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 0.3.0
