name: google_sign_in_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_identity_services_web: ^0.2.0
  google_sign_in_platform_interface: ^2.2.0
  google_sign_in_web:
    path: ../

flutter:
  uses-material-design: true

dependency_overrides:
  google_identity_services_web:
    git:
      url: https://github.com/ditman/flutter-packages.git
      ref: gis-web-fix-render-button-api
      path: packages/google_identity_services_web
  google_sign_in_platform_interface:
    path: ../../google_sign_in_platform_interface

dev_dependencies:
  build_runner: ^2.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  integration_test:
    sdk: flutter
  js: ^0.6.3
  mockito: 5.4.0
