name: local
description: Example of new custom local widgets for RFW
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  rfw:
    path: ../../
