name: flutter_service_worker
description: Flutter package for integrating with the web Service Worker
homepage: https://github.com/flutter/packages/tree/master/packages/flutter_service_worker
version: 0.0.1
authors:
  - Jonah Williams <jonahwilliams@google.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: 1.1.8

dev_dependencies:
  test: 1.14.3