name: google_adsense_ad_placement_api
description: Dart classes to interact with Google's AdSense Ad Placement API
version: 0.0.1
repository: https://github.com/flutter/packages/google_adsense_ad_placement_api

environment:
  sdk: ^3.4.4

dependencies:
  web: "^1.1.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

platforms:
  web:
