name: pigeon_example_app
description: An example of using Pigeon in an application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
