name: google_adsense_ad_placement_api_web_example
description: An example for the google_adsense_ad_placement_api_web_example package.
publish_to: 'none'

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_adsense_ad_placement_api_web:
    path: ../
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
