name: web_benchmarks
description: A benchmark harness for performance-testing Flutter apps in Chrome.
repository: https://github.com/flutter/packages/tree/main/packages/web_benchmarks
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+web_benchmarks%22
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ^1.0.2
  meta: ^1.8.0
  path: ^1.8.2
  process: ^4.2.4
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  test: ^1.21.4
  webkit_inspection_protocol: ^1.1.0
