name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.
publish_to: none

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  webview_flutter:
    # When depending on this package from a real application you should use:
    #   webview_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  webview_flutter_android:
    git:
      url: https://github.com/Sinishisimus/packages.git
      path: packages/webview_flutter/webview_flutter_android
      ref: feature/android_web_view_render_process_terminated
  webview_flutter_wkwebview:
    git:
      url: https://github.com/Sinishisimus/packages.git
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: feature/android_web_view_render_process_terminated

dev_dependencies:
  build_runner: ^2.1.5
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  webview_flutter_platform_interface:
    git:
      url: https://github.com/Sinishisimus/packages.git
      path: packages/webview_flutter/webview_flutter_platform_interface
      ref: feature/android_web_view_render_process_terminated

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
