name: stager
description: A Flutter productivity tool that allows developers to isolate pieces of UI.
version: 0.1.0
repository: https://github.com/flutter/packages/stager
issue_tracker:  https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3Astager

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  flutter:
    sdk: flutter
  source_gen: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
