name: google_maps_flutter_web
description: Web platform implementation of google_maps_flutter
repository: https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
version: 0.5.8

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    implements: google_maps_flutter
    platforms:
      web:
        pluginClass: GoogleMapsPlugin
        fileName: google_maps_flutter_web.dart

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_maps: ^8.0.0-dev.1
  google_maps_flutter_platform_interface: ^2.7.0
  sanitize_html: ^2.0.0
  stream_transform: ^2.0.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  google_maps:
    git:
      url: https://github.com/Rexios80/dart-google-maps
      ref: 0e156160a6d3e6d9b8b7f26603d4f825029c217f

topics:
  - google-maps
  - google-maps-flutter
  - map

# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/web/index.html
