# Specify analysis options.

include: ../../analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false # Standalone executable, no public API
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
