name: pointer_interceptor_web_example
description: "Demonstrates how to use the pointer_interceptor_web plugin."
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  pointer_interceptor:
    path: ../../pointer_interceptor

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

