name: adaptive_scaffold_example
description: Multiple examples of the usage of the AdaptiveScaffold widget and its lower level widgets.

publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations:
    path: ../../adaptive_scaffold
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true