name: adaptive_scaffold_example
description: Multiple examples of the usage of the AdaptiveScaffold widget and its lower level widgets.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  adaptive_scaffold:
    path: ../../adaptive_scaffold
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/noodles.png
    - images/plant-based.png
    - images/user.png
    - images/singapore.png
    - images/woman.png
    - images/woman2.png
    - images/young-man.png
    - images/man.png
    - images/yoga.png
    - images/beauty.png

  
