name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera_avfoundation:
  camera_platform_interface:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  quiver: ^3.0.0
  video_player: ^2.1.4

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

# TODO: for PR
dependency_overrides:
  camera_avfoundation:
    path: ../
  camera_platform_interface:
    path: ../../../camera/camera_platform_interface
