name: file_selector_android
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    implements: file_selector
    platforms:
      android:
        package: io.flutter.plugins.file_selector_android
        pluginClass: FileSelectorAndroidPlugin

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: 5.4.0
  pigeon: ^9.2.4
