name: dart_ui_web_shim
description: A shim so dart analyze doesn't complain about web-only parts of the dart:ui package.
repository: https://github.com/flutter/packages/tree/master/packages/dart_ui_web_shim
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+dart_ui_web_shim%22
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
