name: flutter_lints
description: Recommended lints for Flutter apps, packages, and plugins
version: 0.1.0
homepage: https://github.com/flutter/packages/tree/master/packages/flutter_lints
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lints: # TODO(goderbauer): depend on released version before releasing the package
    git: https://github.com/dart-lang/lints.git
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
