name: multicast_dns
description: Dart package for mDNS queries (e.g. Bonjour, Avahi).
homepage: https://github.com/flutter/packages/tree/master/packages/multicast_dns
version: 1.0.0-nullsafety

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mockito: ^5.0.0-nullsafety.7
  test: ^1.16.2

environment:
  sdk: '>=2.12.0-0 <3.0.0'
