name: interactive_media_ads
description: "Flutter plugin for the Interactive Media Ads SDKs."
repository: https://github.com/flutter/packages/tree/main/packages/interactive_media_ads
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+interactive_media_ads%22
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.interactive_media_ads
        pluginClass: InteractiveMediaAdsPlugin
      ios:
        pluginClass: InteractiveMediaAdsPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: 5.4.4

topics:
  - ads
