name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.7.0
  google_maps_flutter_web:
    path: ../
  web: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  google_maps: ^8.0.0-dev.1
  google_maps_flutter: ^2.2.0 # Needed for projection_test.dart
  http: ^1.0.0
  integration_test:
    sdk: flutter
  mockito: 5.4.4

flutter:
  assets:
    - assets/

dependency_overrides:
  google_maps:
    git:
      url: https://github.com/Rexios80/dart-google-maps
      ref: 0e156160a6d3e6d9b8b7f26603d4f825029c217f
  # Override the google_maps_flutter dependency on google_maps_flutter_web.
  # TODO(ditman): Unwind the circular dependency. This will create problems
  # if we need to make a breaking change to google_maps_flutter_web.
  google_maps_flutter_web:
    path: ../
